config/routes.rb
Rails.application.routes.draw do
  resources :furnitures
  resources :rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/furniture.rb
class Furniture < ApplicationRecord
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/furnitures_controller.rb
class FurnituresController < ApplicationController
  before_action :set_furniture, only: %i[ show edit update destroy ]

  # GET /furnitures or /furnitures.json
  def index
    @furnitures = Furniture.all
  end

  # GET /furnitures/1 or /furnitures/1.json
  def show
  end

  # GET /furnitures/new
  def new
    @furniture = Furniture.new
  end

  # GET /furnitures/1/edit
  def edit
  end

  # POST /furnitures or /furnitures.json
  def create
    @furniture = Furniture.new(furniture_params)

    respond_to do |format|
      if @furniture.save
        format.html { redirect_to furniture_url(@furniture), notice: "Furniture was successfully created." }
        format.json { render :show, status: :created, location: @furniture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @furniture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /furnitures/1 or /furnitures/1.json
  def update
    respond_to do |format|
      if @furniture.update(furniture_params)
        format.html { redirect_to furniture_url(@furniture), notice: "Furniture was successfully updated." }
        format.json { render :show, status: :ok, location: @furniture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @furniture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /furnitures/1 or /furnitures/1.json
  def destroy
    @furniture.destroy

    respond_to do |format|
      format.html { redirect_to furnitures_url, notice: "Furniture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_furniture
      @furniture = Furniture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def furniture_params
      params.require(:furniture).permit(:name, :color, :height, :weight, :function, :room_id)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :sqft, :windows, :doors, :color, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/furnitures_helper.rb
module FurnituresHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/furnitures/_form.html.erb
<%= form_with(model: furniture) do |form| %>
  <% if furniture.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(furniture.errors.count, "error") %> prohibited this furniture from being saved:</h2>

      <ul>
        <% furniture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :color, style: "display: block" %>
    <%= form.text_field :color %>
  </div>

  <div>
    <%= form.label :height, style: "display: block" %>
    <%= form.text_field :height %>
  </div>

  <div>
    <%= form.label :weight, style: "display: block" %>
    <%= form.text_field :weight %>
  </div>

  <div>
    <%= form.label :function, style: "display: block" %>
    <%= form.text_field :function %>
  </div>

  <div>
    <%= form.label :room_id, style: "display: block" %>
    <%= form.text_field :room_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/furnitures/_furniture.html.erb
<div id="<%= dom_id furniture %>">
  <p>
    <strong>Name:</strong>
    <%= furniture.name %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= furniture.color %>
  </p>

  <p>
    <strong>Height:</strong>
    <%= furniture.height %>
  </p>

  <p>
    <strong>Weight:</strong>
    <%= furniture.weight %>
  </p>

  <p>
    <strong>Function:</strong>
    <%= furniture.function %>
  </p>

  <p>
    <strong>Room:</strong>
    <%= furniture.room_id %>
  </p>

</div>

app/views/furnitures/edit.html.erb
<h1>Editing furniture</h1>

<%= render "form", furniture: @furniture %>

<br>

<div>
  <%= link_to "Show this furniture", @furniture %> |
  <%= link_to "Back to furnitures", furnitures_path %>
</div>

app/views/furnitures/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Furnitures</h1>

<div id="furnitures">
  <% @furnitures.each do |furniture| %>
    <%= render furniture %>
    <p>
      <%= link_to "Show this furniture", furniture %>
    </p>
  <% end %>
</div>

<%= link_to "New furniture", new_furniture_path %>

app/views/furnitures/new.html.erb
<h1>New furniture</h1>

<%= render "form", furniture: @furniture %>

<br>

<div>
  <%= link_to "Back to furnitures", furnitures_path %>
</div>

app/views/furnitures/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @furniture %>

<div>
  <%= link_to "Edit this furniture", edit_furniture_path(@furniture) %> |
  <%= link_to "Back to furnitures", furnitures_path %>

  <%= button_to "Destroy this furniture", @furniture, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>House</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :sqft, style: "display: block" %>
    <%= form.number_field :sqft %>
  </div>

  <div>
    <%= form.label :windows, style: "display: block" %>
    <%= form.number_field :windows %>
  </div>

  <div>
    <%= form.label :doors, style: "display: block" %>
    <%= form.number_field :doors %>
  </div>

  <div>
    <%= form.label :color, style: "display: block" %>
    <%= form.text_field :color %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <p>
    <strong>Name:</strong>
    <%= room.name %>
  </p>

  <p>
    <strong>Sqft:</strong>
    <%= room.sqft %>
  </p>

  <p>
    <strong>Windows:</strong>
    <%= room.windows %>
  </p>

  <p>
    <strong>Doors:</strong>
    <%= room.doors %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= room.color %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= room.description %>
  </p>

</div>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rooms</h1>

<div id="rooms">
  <% @rooms.each do |room| %>
    <%= render room %>
    <p>
      <%= link_to "Show this room", room %>
    </p>
  <% end %>
</div>

<%= link_to "New room", new_room_path %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @room %>

<div>
  <%= link_to "Edit this room", edit_room_path(@room) %> |
  <%= link_to "Back to rooms", rooms_path %>

  <%= button_to "Destroy this room", @room, method: :delete %>
</div>